IP-14110: Ability to create custom api endpoint
iPriceGroup/ocapiplugin pull request #21
Opened 2020-04-21 10:42 UTC by minhtran17

2020-04-21 12:48 UTC, sandyandi requested changes

2020-04-21 12:48 UTC, sandyandi commented on templates/route.tpl
> +Route::%router_method%('%base_endpoint%', '%controller_class%')%middleware_string%;
Let's still use one template:
```suggestion
Route::%router_method%('%base_endpoint%', '%controller_class%'%options%)%route_methods%;
```
`%options%` and `%route_methods%` are optional based on the `%router_method%` used.

2020-04-21 12:48 UTC, sandyandi commented on updates/builder_table_update_ipricegroup_ocapiplugin_resources_add_route_action.php
> +class BuilderTableUpdateIpricegroupOcapipluginResourcesAddRouteAction extends Migration
Do you mean `RouterMethod` instead of `RouteAction`?

Also, the filename should say `router_method` instead of `route_action`.

2020-04-21 12:48 UTC, sandyandi commented on updates/version.yaml
> +    - 'Add route_action to table'
Do you mean `router_method`?

2020-04-22 03:05 UTC, sandyandi requested changes

2020-04-22 03:05 UTC, sandyandi commented on classes/RoutesManager.php
> +        return $this->$variable ?: $this->routeTemplate;
Is this still needed?

2020-04-22 03:05 UTC, sandyandi commented on classes/RoutesManager.php
> +        '%middleware_string%',
Referencing [this comment](https://github.com/iPriceGroup/ocapiplugin/pull/21#discussion_r412153016) - let's call this `route_methods` as that's what the placeholder is generally for. Not only middlewares.

2020-04-22 03:11 UTC, minhtran17 commented on classes/RoutesManager.php
> +        return $this->$variable ?: $this->routeTemplate;
yeah forgot to push :D

2020-04-22 06:34 UTC, sandyandi approved these changes

2020-04-24 04:04 UTC, ahmedzidan approved these changes

2020-05-04 05:15 UTC, merged