Add permission to iPrice RESTful API Generator
iPriceGroup/ocapiplugin pull request #3
Opened 2019-04-19 03:34 UTC by caothang53

## Scenario:

Our plugin iPrice RESTful API Generator can be accessed by a non-admin user because there is no permission for this plugin. This pull request is to add permission for our API Generator plugin so we can restrict non-admin users to access to this plugin.

2019-04-19 03:40 UTC, caothang53 commented
This PR relates to this issue: #4

2019-04-19 03:49 UTC, sandyandi requested changes

2019-04-19 03:49 UTC, sandyandi commented on plugin.yaml
> +        - iprice-restful-api-generator
Please indent properly. Also, I think it's better to give it a more generic permission: `manage_apis`

2019-04-23 01:27 UTC, sandyandi approved these changes

2019-04-23 01:27 UTC, merged